#!/bin/bash
#
# Title:      PlexGuide (rdp-calibre)
# Author(s):  PlexGuide
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0 
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'rdp-calibre'
        intport: '8080'
        extport: '8089'
        intport2: '8081'
        extport2: '8090'
        image: 'aptalca/docker-rdp-calibre:latest'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/pg/data/{{pgrole}}:/config:rw'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/pg/unity:/unity:rw'
          - '/pg:/pg:rw'
          - '/etc/localtime:/etc/localtime:ro'
          - '/pg/unity/libary:/library:rw'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          TZ: '${TZ}'
          WIDTH: '1280'
          HEIGHT: '720'
          
    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '{{ports.stdout}}{{extport2}}:{{intport2}}'		  
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
